variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GET_SOURCES_ATTEMPTS: 3

default:
  before_script:
    - echo $MAKE_TARGET
    - echo $SCRIPT_PATH
    - echo $DUT_PCIADDR
    - ./install.sh
    - make setup
  after_script:
    - make reset    
    - make clean
  
quick_test:
  only:
    - pushes
  script:
    - sudo python3 -B -m pytest driver_test.py::test_ioworker_iops_multiple_queue_fob[1] --pciaddr=01:00.0
    - sudo python3 -B -m pytest driver_test.py::test_ioworker_iops_multiple_queue[1] --pciaddr=10.24.48.17

stress_test:
  except:
    - pushes
  artifacts:
    paths:
      - test.log
    when: always
    expire_in: 1 yrs
  script:
    - make $MAKE_TARGET $SCRIPT_PATH $DUT_PCIADDR
    - cat test.log | grep "457 passed" || exit -1
