variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GET_SOURCES_ATTEMPTS: 3

default:
  before_script:
    - echo $MAKE_TARGET
    - echo $SCRIPT_PATH
    - echo $DUT_PCIADDR
    - ./install.sh
  after_script:
    - make reset
    - make clean
  
checkin_test:
  only:
    - pushes
  script:
    - sudo python3 -B -m pytest driver_test.py::test_ioworker_iops_multiple_queue_fob --pciaddr=0000:06:00.0
    - make setup memsize=4000
    - make nvmt
    - sudo python3 -B -m pytest driver_test.py::test_ioworker_iops_multiple_queue[1] --pciaddr=127.0.0.1
    - cd src; make unittest; cd ..
    - make setup memsize=0

stress_test:
  only:
    - schedules
  artifacts:
    paths:
      - test_.*\.log
    when: always
    expire_in: 5 yrs
  script:
    - make test pciaddr=0000:06:00.0
    - cat test_*.txt | grep "3 failed, 387 passed" || exit -1
    - make setup memsize=4000
    - make nvmt
    - make test TESTS=driver_test_tcp.py pciaddr=0000:06:00.0
    - make setup memsize=0

scripts_test:
  only:
    - web
  artifacts:
    paths:
      - test_.*\.log
      - .*_report.xlsx
      - .*_report.pdf
    when: always
    expire_in: 5 yrs
  script:
    - make test pciaddr=$DUT_PCIADDR TESTS=scripts/$SCRIPT_PATH
    - make setup memsize=0
