variables:
  GIT_SUBMODULE_STRATEGY: recursive

driver_test:
  before_script:
    - echo $MAKE_TARGET
    - echo $SCRIPT_PATH
    - echo $DUT_PCIADDR
  script:
    - ./install.sh
    - make setup
    - make nvmt
    - make $MAKE_TARGET
    - make test TESTS=driver_test.py::test_nvme_tcp_basic
  after_script:
    - mv test.log ../ -f
    - make clean
    - make reset
