variables:
  GIT_SUBMODULE_STRATEGY: recursive

driver_test:
  before_script:
    - echo $MAKE_TARGET
    - echo $SCRIPT_PATH
    - echo $DUT_PCIADDR
    - whoami
    - lspci
    - sudo lspci -s $DUT_PCIADDR -vv
    - date
    - pwd
  script:
    - cd spdk/dpdk; git checkout spdk-18.08; cd ../..
    - sudo ./spdk/scripts/pkgdep.sh
    - sudo pip3 install -r requirements.txt
    - cd spdk; ./configure --without-isal; cd ..   # configurate SPDK
    - make spdk                                    # compile SPDK
    - make                                         # compile pynvme
    - make setup
    - make $MAKE_TARGET
    - make reset
  after_script:
    - sudo ./spdk/scripts/setup.sh status
    - make clean
