variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GET_SOURCES_ATTEMPTS: 3

default:
  before_script:
    - echo $MAKE_TARGET
    - echo $SCRIPT_PATH
    - echo $DUT_PCIADDR
    - ./install.sh
    - make setup
  after_script:
    - make reset
    - make clean
  
checkin_test:
  only:
    - pushes
  script:
    - cd src; make unittest; cd ..
    - sudo python3 -B -m pytest driver_test.py::test_ioworker_iops_multiple_queue_fob --pciaddr=0000:06:00.0
    - make setup memsize=4000; make nvmt
    - sudo python3 -B -m pytest driver_test.py::test_ioworker_iops_multiple_queue[1] --pciaddr=127.0.0.1
    - make setup memsize=0

stress_test:
  only:
    - schedules
  artifacts:
    paths:
      - test.log.txt
    when: always
    expire_in: 5 yrs
  script:
    - make setup memsize=4000; make nvmt
    - make test pciaddr=0000:06:00.0
    - cat test*.log | grep "3 failed, 393 passed" || exit -1
    - mv test*.log test.log.txt

scripts_test:
  only:
    - web
  artifacts:
    paths:
      - test.log.txt
      - performance_report.xlsx
    when: always
    expire_in: 5 yrs
  script:
    - make test pciaddr=$DUT_PCIADDR TESTS=scripts/$SCRIPT_PATH
    - mv test*.log test.log.txt
