variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GET_SOURCES_ATTEMPTS: 3

default:
  before_script:
    - echo $MAKE_TARGET
    - echo $SCRIPT_PATH
    - echo $DUT_PCIADDR
    - ./install.sh
  after_script:
    - make reset
    - make clean
  
checkin_test:
  only:
    - pushes
  script:
    - sudo python3 -B -m pytest driver_test.py::test_ioworker_iops_multiple_queue_fob --pciaddr=0000:06:00.0
    - make setup memsize=4000
    - make nvmt
    - sudo python3 -B -m pytest driver_test.py::test_ioworker_iops_multiple_queue[1] --pciaddr=127.0.0.1
    - cd src; make unittest; cd ..
    - make setup memsize=0

stress_test:
  only:
    - schedules
  artifacts:
    paths:
      - test.log.txt
    when: always
    expire_in: 5 yrs
  script:
    - make test pciaddr=0000:06:00.0
    - mv test*.log test.log.txt
    - cat test.log.txt | grep "3 failed, 387 passed, 6 skipped" || exit -1
    - make setup memsize=4000
    - make nvmt
    - sudo python3 -B -m pytest driver_test.py::test_nvme_tcp_basic
    - sudo python3 -B -m pytest driver_test.py::test_nvme_tcp_ioworker
    - sudo python3 -B -m pytest driver_test.py::test_two_controllers
    - sudo python3 -B -m pytest driver_test.py::test_two_namespace_basic
    - sudo python3 -B -m pytest driver_test.py::test_two_namespace_ioworkers
    - make setup memsize=0

scripts_test:
  only:
    - web
  artifacts:
    paths:
      - test.log.txt
      - performance_report.xlsx
    when: always
    expire_in: 5 yrs
  script:
    - make test pciaddr=$DUT_PCIADDR TESTS=scripts/$SCRIPT_PATH
    - mv test*.log test.log.txt
    - make setup memsize=0
