variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GET_SOURCES_ATTEMPTS: 3

default:
  before_script:
    - echo $MAKE_TARGET
    - echo $SCRIPT_PATH
    - echo $DUT_PCIADDR
    - ./install.sh
    - make setup memsize=8000
  after_script:
    - make reset
    - make clean
  
checkin_test:
  only:
    - pushes
  script:
    - sudo python3 -B -m pytest driver_test.py::test_ioworker_iops_multiple_queue_fob --pciaddr=01:00.0
    - sudo python3 -B -m pytest driver_test.py::test_ioworker_iops_multiple_queue[1] --pciaddr=10.24.48.17
    - cd src; make unittest

stress_test:
  only:
    - schedules
  artifacts:
    paths:
      - test*.log
    when: always
    expire_in: 5 yrs
  script:
    - make test pciaddr=0000:01:00.0
    - cat test*.log | grep "3 failed, 393 passed" || exit -1

scripts_test:
  only:
    - web
  artifacts:
    paths:
      - test*.log
      - performance_report.xlsx
    when: always
    expire_in: 5 yrs
  script:
    - make test pciaddr=$DUT_PCIADDR TESTS=scripts/$SCRIPT_PATH
