variables:
  GIT_SUBMODULE_STRATEGY: recursive

driver_test:
  before_script:
    - echo $MAKE_TARGET
    - echo $SCRIPT_PATH
    - echo $DUT_PCIADDR
  script:
    - ./install.sh
    - make setup
    - cd spdk/app/nvmf_tgt/; make
    - make nvmt
    - make $MAKE_TARGET
    - make $MAKE_TARGET
  after_script:
    - mv test.log ../ -f
    - make clean
    - make reset
