variables:
  GIT_SUBMODULE_STRATEGY: recursive

driver_test:
  before_script:
    - echo $MAKE_TARGET
    - echo $SCRIPT_PATH
    - echo $DUT_PCIADDR
    - whoami
    - lspci
    - sudo lspci -s $DUT_PCIADDR -vv
    - date
    - pwd
    - sudo ./spdk/scripts/pkgdep.sh
    - sudo dnf install python3-pip -y # Ubuntu: sudo apt-get install python3-pip 
    - sudo python3 -m pip install -r requirements.txt
    - cd spdk; ./configure --without-isal; cd ..   # configurate SPDK
    - make spdk                     # compile SPDK
    - make                          # compile pynvme
    - ls
    - make setup
    - sudo ./spdk/scripts/setup.sh status
  script:
    - make $MAKE_TARGET
  after_script:
    - make clean
    - sudo ./spdk/scripts/setup.sh status
