variables:
  GIT_SUBMODULE_STRATEGY: recursive

driver_test:
  before_script:
    - echo $MAKE_TARGET
    - echo $SCRIPT_PATH
    - echo $DUT_PCIADDR
    - whoami
    - lspci
    - sudo lspci -s $DUT_PCIADDR -vv
    - date
    - pwd
  script:
    - ./install.sh
    - make setup
    - make $MAKE_TARGET
    - make reset
  after_script:
    - sudo ./spdk/scripts/setup.sh status
    - make clean
